# -*- coding: utf-8 -*-
"""Projeto_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wr4rJszMvYiqOtBl0bPjz-JjzwFJ1pnD
"""

while True:
  # Solicitar o primeiro número
  num1 = input('Digite o primeiro número: ')
  num2 = input('Digite o segundo número: ')

  # Verificar se o input foram de números válidos
  if (num1.replace('.', '', 1).isdigit() or num1.replace(',', '', 1).isdigit()) and (num2.replace('.', '', 1).isdigit() or num2.replace(',', '', 1).isdigit()):
    # Convertendo as entradas para float
    num1 = float(num1.replace(',', '.'))
    num2 = float(num2.replace(',', '.'))
  else:
    print('Por favor, insira valores númericos válidos.')
    continue

  # Exibir as operações que o usuário pode escolher
  print('\nEscolha uma operação:')
  print('1. Soma')
  print('2. Subtração')
  print('3. Multiplicação')
  print('4. Potenciação')
  print('5. Divisão')
  print('6. Sair')

  # Solicitação para o usuário escolher uma operação
  operacao = input('\nDigite o número da operação desejada: ')

  # Efetua a operação que foi escolhida e da o print no resultado
  if operacao == '1':
    resultado = num1 + num2
    print(f'\nResultado da soma {resultado}\n')
  elif operacao == '2':
    resultado = num1 - num2
    print(f'\nResultado da subtração {resultado}\n')
  elif operacao == '3':
    resultado = num1 * num2
    print(f'\nResultado da multiplicação {resultado}\n')
  elif operacao == '4':
    resultado = num1 ** num2
    print(f'\nResultado da potenciação {resultado}\n')
  elif operacao == '5':
    if num2 != 0:
      resultado = num1 / num2
      print(f'\nResultado da divisão {resultado}\n')
    else:
      print('Não é possivel dividir por zero.')
  elif operacao == '6':
    print('Fechando programa.')
    break
  else:
    print('Operação inválida. Por favor, tente novamente.')

  # Evita que a pessoa precise preencher num1 e num2 novamente para fechar a calculadora.
  while True:
    exit = input('Você deseja realizar outra operação? (S/N): ').upper()
    if exit in ['S', 'N']:
      break
    else:
      print('Entrada inválida! Por favor, insira "S" para sim ou "N" para não.\n')

  if exit == 'N':
    break

